// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/gc_free_screen_logic.dart';
import 'api/instant_free_screen_logic.dart';
import 'api/leaked_screen_logic.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_GcFreeScreenLogicPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_InstantFreeScreenLogicPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_LeakedScreenLogicPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic;

  @protected
  GcFreeScreenLogic
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          dynamic raw);

  @protected
  InstantFreeScreenLogic
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          dynamic raw);

  @protected
  LeakedScreenLogic
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          dynamic raw);

  @protected
  GcFreeScreenLogic
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          dynamic raw);

  @protected
  InstantFreeScreenLogic
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          dynamic raw);

  @protected
  LeakedScreenLogic
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          dynamic raw);

  @protected
  GcFreeScreenLogic
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          dynamic raw);

  @protected
  InstantFreeScreenLogic
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          dynamic raw);

  @protected
  LeakedScreenLogic
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          dynamic raw);

  @protected
  GcFreeScreenLogic
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          dynamic raw);

  @protected
  InstantFreeScreenLogic
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          dynamic raw);

  @protected
  LeakedScreenLogic
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  int dco_decode_usize(dynamic raw);

  @protected
  GcFreeScreenLogic
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          SseDeserializer deserializer);

  @protected
  InstantFreeScreenLogic
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          SseDeserializer deserializer);

  @protected
  LeakedScreenLogic
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          SseDeserializer deserializer);

  @protected
  GcFreeScreenLogic
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          SseDeserializer deserializer);

  @protected
  InstantFreeScreenLogic
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          SseDeserializer deserializer);

  @protected
  LeakedScreenLogic
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          SseDeserializer deserializer);

  @protected
  GcFreeScreenLogic
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          SseDeserializer deserializer);

  @protected
  InstantFreeScreenLogic
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          SseDeserializer deserializer);

  @protected
  LeakedScreenLogic
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          SseDeserializer deserializer);

  @protected
  GcFreeScreenLogic
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          SseDeserializer deserializer);

  @protected
  InstantFreeScreenLogic
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          SseDeserializer deserializer);

  @protected
  LeakedScreenLogic
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_usize(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          GcFreeScreenLogic self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          InstantFreeScreenLogic self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          LeakedScreenLogic self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          GcFreeScreenLogic self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          InstantFreeScreenLogic self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          LeakedScreenLogic self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          GcFreeScreenLogic self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          InstantFreeScreenLogic self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          LeakedScreenLogic self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          GcFreeScreenLogic self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          InstantFreeScreenLogic self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          LeakedScreenLogic self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          dynamic ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          dynamic ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          dynamic ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          dynamic ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          dynamic ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          dynamic ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
class RustLibWasmModule implements WasmModule {
  @override
  external Object /* Promise */ call([String? moduleName]);

  @override
  external RustLibWasmModule bind(dynamic thisArg, String moduleName);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          dynamic ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockGCFreeScreenLogic(
          dynamic ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          dynamic ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockInstantFreeScreenLogic(
          dynamic ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          dynamic ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockLeakedScreenLogic(
          dynamic ptr);
}
