// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::rust_async::RwLock<LeakedScreenLogic>>
@sealed
class LeakedScreenLogic extends RustOpaque {
  LeakedScreenLogic.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  LeakedScreenLogic.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LeakedScreenLogic,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LeakedScreenLogic,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_LeakedScreenLogicPtr,
  );

  void allocateMemory({dynamic hint}) =>
      RustLib.instance.api.leakedScreenLogicAllocateMemory(
        that: this,
      );

  static LeakedScreenLogic newLeakedScreenLogic({dynamic hint}) =>
      RustLib.instance.api.leakedScreenLogicNew(hint: hint);

  Future<void> receiveData({dynamic hint}) =>
      RustLib.instance.api.leakedScreenLogicReceiveData(
        that: this,
      );

  Stream<int> setSink({dynamic hint}) =>
      RustLib.instance.api.leakedScreenLogicSetSink(
        that: this,
      );
}
